num_1 = int(input("Enter the first number:  "))
num_2 = int(input("Enter the second number:  "))
operator =input("Which operator do you want to use? ,{+ , - , / , *} : ")
if operator == "+": print(num_1 + num_2) 
elif operator == "-": print(num_1 = num_2)
elif operator == "/": print(num_1/num_2)
elif operator == "*": print(num_1*num_2)
else : print("input a valid operator")